### ISSUE TITLE
Making it compatible with android?

### ISSUE THREAD

**Issue by S4rtox** [MCCTeam/Minecraft-Console-Client#1000]
I've been using this client for a long time and I realised that it would be a lot better if we could use this tool for mobiles. I actually dont know if this is possible or achievable, but it would be a lot easier if we could use our mobiles instead of leaving the pc turned on for that purpose. Just a question/suggestion.

Btw thanks @ORelio for keeping woring on this project!, it helps a lot of people.

**Comment by Frog-Lover-Antony** [comment]
@UltimateSartox If you _really_ want to run it on android I suggest setting up Termux.
That will cost you around 200mb of space (40mb app, 50mb bare linux core, 140mb of `mono-devel` packages) and 40-150 mb RAM for each shell running.
If you wish to do so, I can help you.

**Comment by UltimateSartox** [comment]
Oh the termux seems like a good idea, I don't know how to set it up, byt if you can help me to do it I would appreciate it, thanks for being that nice btw

**Comment by Frog-Lover-Antony** [comment]
@UltimateSartox give me a couple hours, I will provide you a full instruction today

**Comment by Frog-Lover-Antony** [comment]
### Termux install

1. First things first, you need to install Termux from Google Play or any source avalable.

2. Run Termux and let it download all necessary files and libaries.

3. When you will be able to use the command prompt and create new shell instances _(by sliding left to right on your screen)_, type
`pkg get update`
and
`pkg install mono-devel`
This process might take some time, but hopefully should install all necessary libaries for `mono`

!!Mono is probably not supported for Termux, if you have any trouble installing `mono`, consider following those instructions on [building mono](https://github.com/IanusInferus/termux-mono) !!

_Dont't be afraid to ask if me anything goes wrong, I know that getting started with linux and stuff is difficult. also, this guide might be not 100% accurate due to my dumb*** typing everything by memory and not testing it myself. I don't even know if it works on Android since I tested everything this way on raspberry yesterday._

### Getting started with MCC

1. Test `git` package by typing `git`.
If Termux tells you "no such package" or any "package not exist error" do:
`pkg install git`
(to install git)

2. Now, we need to get our client. We now have two options:
	1. using prebuilt executable (easy and might not work)
	2. building everything yourself (difficult, could not do it myself.)

### Build variant 1
Goto install folder you like (you're gonna download the files and use the client from INSIDE the Termux directory, accesible form youe phone, while Termux CAN'T ACCES your phone memory)
**(To see files if the folder you currently are use `ls`, to move a directory higher use `cd ..` to move to a directory you see inside any other directory use `cd ^NAME^`. To create a new directory use `mkdir ^NAME^. Your current path is displayed before the type prompt etc. `/user>`)**

When you chose your path, type
`wget https://ci.appveyor.com/api/buildjobs/jyl5nvgv6rwqs4pg/artifacts/MinecraftClient%2Fbin%2FRelease%2FMinecraftClient.exe`
(if you wish grabbing only the .exe file),

Or you can also get all the files like "example-scripts-and-stuff" with
`git clone https://github.com/ORelio/Minecraft-Console-Client.git` (but this makes a new directory. Anyway, don't worry. moving files is easy.)

Well, now you probably have `MinecraftClient%2Fbin%2FRelease%2FMinecraftClient.exe` or all the files inside a folder. Let's fix the name for the first case. 
To reanme/move files linux uses `mv ^NAME^ ^NEWNAME^`. Type in `mv MinecraftClient%2Fbin%2FRelease%2FMinecraftClient.exe MCC.exe` (or use whatever you like instead of `MCC.exe`)

OK. Got the executable? Great! that's the moment of truth! Run
`mono MCC.exe`
And see if it runs.

Basically, at this moment you already should know how to use the program and set it up.
To create new files for your configs (like servers.txt) use `touch ^FILENAME^`. This creates a blank file. To edit it, I suggest `nano` as a simple text editor. (try `nano ^FILENAME^` and you should understand it well.)

**`nano` uses CTRL+S to save, CTRL+X to exit, CTRL+C to background it (`fg` will open the last backgrounded app). You can copy text with COMMAND+M and paste with something similar but I always forget how to, so just use the "paste" button inside Termux.**

### Build variant 2 (for the brave)
I literally have  no idea why couldn't I do it myself.
Try following [official and not working tutorial](https://github.com/ORelio/Minecraft-Console-Client#on-mac-and-linux)
And please, tell me if you have any success with it 
**btw on newer mono versions `msbuild` = `mcs` or whatever**

### Scripting, running, making your life easier
Lets'start with the last one. Linux can do `aliases`. Think of a shortcut on Windows. This is basically it, but in cmd.
To alias our new executable do this:
`sudo nano /data/data/com.termux/files/usr/etc/bash.bashrc`
**!!THIS OPENS THE BASHRC FILE IN FULL ACESS MODE!! FOR THE LOVE OF GOD, DO NOT CHANGE ANYTHING YOU DON'T UNDERSTAND IN IT!!**
Ok, warnings behind. Now, do a simple thing. Go to the end of this file and write
`alias ^name you would like to run MCC with^="cd /^path to MCC.exe folder^/; mono MCC.exe"` (you can use whatever names you like)
now, after restarting your consoles and Termux, type your alias name.

**OwO what's this? An easy way to start the console??**

Scripting... You know how it all works. Copy all your beloved configs from PC or create new ones. On now, everything is absolutely the same as on PC.
**Don't forget that in case of emergency, you can always terminate the process with CTRL+C.**

### Multiaccounting
Termux supports opening multiple shells. Open a new one -> start MCC. Easy.

### Hopefully, end of installation.
I'm sure, a lot of problems will come up during the process, but I will try to help you as much as I can.

**Comment by Frog-Lover-Antony** [comment]
@ORelio, I suggest making this an official guide

**Comment by ORelio** [comment]
Very nice subject for the #1000th issue 🥳

Porting MCC to Android would be quite a challenge since MCC is written using C#.NET, not Java.

@Frog-Lover-Antony your approach seems really cool, setting up Mono on Android can indeed be used to launch MCC. Definitely worth integrating in the user manual or as a separate (but official) manual. Adding this to the TODO list 👍

**Comment by CarsondaCoolest** [comment]
Hey @Frog-Lover-Antony ! I've been trying to follow these instructions to get this working on my phone, and unfortunately I've run into an issue with "PKG install mono-devel" resulting in "

**Comment by yougeshlama** [comment]
I have found the source code for android app but i dont know to compile it can any body help me.
here is the link(https://github.com/nekonekokun/Minecraft-Console-Client-Android)

**Comment by ORelio** [comment]
Was not aware of this repository. Ask the author, @nekonekokun

**Comment by yougeshlama** [comment]
he is not active since 6 years.
@ORelio

**Comment by ORelio** [comment]
I have no idea how to use their code. Maybe it's not even functional.

**Comment by yougeshlama** [comment]
:(

**Comment by xXjojaXx** [comment]
May be cool to reawake this issue an actually do a java versin for mcc with exact same functionality, if someone has time. Would be very ressource cheap to use and a cool idea, but if theres not enough time, like it seems in the moment, probably not worth the effort.

**Comment by ORelio** [comment]
@xXjojaXx You would need to re-code almost everything if you want to port MCC to Java. However, I think it's possible to make an Android app containing the Mono runtime and MCC's assembly, and in that case only the UI would need to contain Android-specific Java code.

**Comment by xXjojaXx** [comment]
Maybe really doing this. I kinda got into Android/javaProgramming in the moment

**Comment by ORelio** [comment]
I think if you manage to get the assembly running you've done half of the work, the rest being making a suitable Android UI 😄

**Comment by xXjojaXx** [comment]
After spending some time with it, I think using xamarin, because its running on mono and has many similaritys to the current used infrastructure of mcc (can keep 90% of code and have the opportunity to merge functions in directly in c# (apart of the UI)), probably is the best option to get it working on android with just some little tweaks. Started trying getting it to work but of course there has to be a new option for input and output on android and it seems that this may be a lot of work, which might take some time, because the ConsoleIO class and some console.readlines which are spreaded around the code have to replaced with the new system. To get started I'm maybe using textfield to port the console functionalitys to android 1 to 1 and later on slowely port the textinput to a proper Android UI.

**Comment by ORelio** [comment]
Hi,

Thanks for working on this. No pressure, take your time, that's a big feature.

I think using a [Bridge](https://en.wikipedia.org/wiki/Bridge_pattern) could be nice, as done is other parts of the project. Basically, you create an Interface like [IMinecraftCom](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/IMinecraftCom.cs) then you can have both [ConsoleIO](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ConsoleIO.cs) and your new implementation for Android. The client could then load the appropriate one, just like it loads [Protocol16](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol16.cs) or [Protocol18](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs) depending on the Minecraft version.

**Comment by milutinke** [comment]
Now possible to run the MCC on Android using Termux and .NET Core 6.
Manual on how to do it: https://mccteam.github.io/guide/installation.html#run-on-android
