### ISSUE TITLE
Entity handling for older Minecraft versions

### ISSUE THREAD

**Issue by railroadss** [MCCTeam/Minecraft-Console-Client#1523]
Could you update the entity handling for version 1.8 or 1.8.9?

**Comment by milutinke** [comment]
This requires a lot of work, since entity, block and item mappings are way different 1.8
I doubt anyone would work on this since it requires a lot of work, by a lot I mean really a lot, whoever wanted to work on it would have to manually map all of the items, entities and blocks with all of their variants.
And on top of that he would need to implement a bunch of packets for 1.8 - 1.10

**Comment by milutinke** [comment]
Actually implemented it, only Entity Metadata Packet is left.

**Comment by milutinke** [comment]
I am unable to solve the issue, I'll port the changes to the latest version of the client and I'll just disable entity metadata packet for 1.8 until someone fixes it.

**Comment by milutinke** [comment]
> Could you update the entity handling for version 1.8 or 1.8.9?

We finally did it, #2462 
Note: We still haven't implemented item and block palettes, so the inventory handling is disabled until we do it.
Unfortunately this needs to be done manually, so it will take some time.
