### ISSUE TITLE
[BUG] Commands Not Working

### ISSUE THREAD

**Issue by PythonJoshua** [MCCTeam/Minecraft-Console-Client#1725]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.12.2

### Console Client Version

Latest Version

### Expected Behavior

Responses from when a command is ran in a minecraft server.

### Actual Behavior

I am trying to make a bot for an anarchy server to respond to commands etc, however it is not responding when doing commands.

Code:

```
[Match]
match=30
actionother=send ExcelBOT is now online and working! Please do !help to see the commands!
ownersonly=true

[Match]
match=!help
actionprivate=send /tell $u Hello! Here is the list of commands!
actionother=send Commands: !tps - Server TPS. !suicide - Kills the bot. !walk - Makes the bot walk north. !stopwalk - Stops the bot from walking. !30BOT - I will talk to you.
ownersonly=false

[Match]
match=!tps
actionprivate=send /tell $u Hello! Here is the TPS!
actionother=send The Current TPS is [tps]! I wonder how much it will be later?
ownersonly=false

[Match]
match=!suicide
actionprivate=send /tell $u Nooo! I don't want to die, I am to young!
actionother=send Goodbye Cruel World, I may or may not have commited uhh...
ownersonly=true

[Match]
match=2b2t
actionprivate=send /tell $u You ruined the chain without saying the word..
actionother=send Good job, you had to send it, didn't you?
ownersonly=false

```

### Steps to Reproduce the bug

1. Copy and paste the code into your matches.ini.
2. Join a server, type a command and it won't send.
3. 

### Anythings that could help diagnosing the bug

```txt
Unhandled Exception: System.IO.InvalidDataException: Failed to process incoming packet of type BlockChange. (PacketID: 11, Protocol: 340, LoginPhase: False, InnerException: System.IndexOutOfRangeException). ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MinecraftClient.Mapping.World.SetBlock(Location location, Block block)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

eliteanarchy.org

**Comment by ORelio** [comment]
Hi,

Regarding chat message detection, please look at this:

https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages
> Detecting chat messages
> ------
> Minecraft Console Client can parse messages from the server in order to detect private and public messages.
This is useful for reacting to messages eg when using the AutoRespond, Hangman game, or RemoteControl bots.
However, for unusual chat formats, so you may need to tinker with the ChatFormat section `MinecraftClient.ini`. This section defines the chat format by the means of regular expressions. Building regular expressions can be a bit tricky, so you might want to try them out eg on https://regex101.com - See also issue [#1640](https://github.com/ORelio/Minecraft-Console-Client/issues/1640) for more explanations on regular expressions. You can test that your MCC instance properly detects chat messages using [`sample-script-with-chatbot.cs`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs).

Regarding the exception you posted, it's a missing field error in a 1.12.2 "block change" packet

https://wiki.vg/index.php?title=Protocol&oldid=14204#Block_Change

I've checked the source code and MCC does parse it correctly (correct packet ID, correct packet contents):

https://github.com/ORelio/Minecraft-Console-Client/blob/982f358bf37b69ac1d99887887d71fe86226a2fb/MinecraftClient/Protocol/Handlers/PacketPalettes/PacketPalette1122.cs#L23

https://github.com/ORelio/Minecraft-Console-Client/blob/982f358bf37b69ac1d99887887d71fe86226a2fb/MinecraftClient/Protocol/Handlers/Protocol18.cs#L634

So maybe you got disconnected from the server and MCC failed to parse the packet because it was incomplete, but I think it wasn't actually a bug.

**Comment by PythonJoshua** [comment]
> Hi,
> 
> Regarding chat message detection, please look at this:
> 
> https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages
> 
> > ## Detecting chat messages
> > Minecraft Console Client can parse messages from the server in order to detect private and public messages.
> > This is useful for reacting to messages eg when using the AutoRespond, Hangman game, or RemoteControl bots.
> > However, for unusual chat formats, so you may need to tinker with the ChatFormat section `MinecraftClient.ini`. This section defines the chat format by the means of regular expressions. Building regular expressions can be a bit tricky, so you might want to try them out eg on https://regex101.com - See also issue [#1640](https://github.com/ORelio/Minecraft-Console-Client/issues/1640) for more explanations on regular expressions. You can test that your MCC instance properly detects chat messages using [`sample-script-with-chatbot.cs`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs).
> 
> Regarding the exception you posted, it's a missing field error in a 1.12.2 "block change" packet
> 
> https://wiki.vg/index.php?title=Protocol&oldid=14204#Block_Change
> 
> I've checked the source code and MCC does parse it correctly (correct packet ID, correct packet contents):
> 
> https://github.com/ORelio/Minecraft-Console-Client/blob/982f358bf37b69ac1d99887887d71fe86226a2fb/MinecraftClient/Protocol/Handlers/PacketPalettes/PacketPalette1122.cs#L23
> 
> https://github.com/ORelio/Minecraft-Console-Client/blob/982f358bf37b69ac1d99887887d71fe86226a2fb/MinecraftClient/Protocol/Handlers/Protocol18.cs#L634
> 
> So maybe you got disconnected from the server and MCC failed to parse the packet because it was incomplete, but I think it wasn't actually a bug.

hi, im a beginner to this im not to sure if i understand fully, so is this the minecraft servers problem? I have tried on multiple servers on multiple versions with the same error output.
