### ISSUE TITLE
Suggestion: make into a mod

### ISSUE THREAD

**Issue by j-romchain** [MCCTeam/Minecraft-Console-Client#1772]
Would it be plausibly easier to start with minecraft and turn it into a command prompt than to make a command prompt for minecraft? Aka start with a 20 foot high tower, and remove 15 feet, rather than making 5 feet.

**Comment by ORelio** [comment]
That's an interesting idea. Due to Minecraft being made to run graphically, removing the GUI might cause unforeseen issues, but it should definitely be possible to make a console mod for it, especially chat only.

However:

1. When modding Minecraft, you need to decompile the game and deobfuscate the classes (i-e. reverse engineer the structure of the source code). This takes significant time although someone else can do it for you (e.g. Mod Coder Pack) but then you need to wait for a new version of said coder pack
2. Finally, for every new Minecraft version, you'd need to accomodate to the changes in the source code, pretty much similarly to the Bukkit or Forge APIs that need updates for any new Minecraft versions
3. Minecraft is very resource intensive so even modded to be console-only, Minecraft would consume much more resources than Minecraft Console Client.

For all of these reasons, I think that on the long term, a mod would require more work than maintaining a separate application.

**Comment by ORelio** [comment]
I'm marking your issue as a won't fix since it would be a completely different project, but thanks for suggesting, nice idea 👍
