### ISSUE TITLE
Extremely high data usage

### ISSUE THREAD

**Issue by jcodyparker** [MCCTeam/Minecraft-Console-Client#1779]
In the past 30 days, 10 accounts afk 24/7 have used over 2000gb of data. This seems extremely high, is something wrong? Is this a server or client side issue? Terrain movements is set to false already.

**Comment by ORelio** [comment]
Despite terrain and movement being set to false, chunks are sent by the server anyway because vanilla Minecraft cannot disable terrain so there is no way to tell the server not to send chunks. This may lead to high data usage. 2000 gb for 30 days, 10 accounts gives around 77kbps per account. This value seems plausible for Minecraft multiplayer if we take chunks into account.

**Comment by jcodyparker** [comment]
> Despite terrain and movement being set to false, chunks are sent by the server anyway because vanilla Minecraft cannot disable terrain so there is no way to tell the server not to send chunks. This may lead to high data usage. 2000 gb for 30 days, 10 accounts gives around 77kbps per account. This value seems plausible for Minecraft multiplayer if we take chunks into account.

Some accounts have 200gb used, some have anywhere from 8gb to 50gb used. Any clue why some accounts dont use much at all compared to the 200gb ones? They all have chat messages turned of and afking the same type of farm in the same area.

**Comment by CelestialParagon** [comment]
> > Despite terrain and movement being set to false, chunks are sent by the server anyway because vanilla Minecraft cannot disable terrain so there is no way to tell the server not to send chunks. This may lead to high data usage. 2000 gb for 30 days, 10 accounts gives around 77kbps per account. This value seems plausible for Minecraft multiplayer if we take chunks into account.
> 
> Some accounts have 200gb used, some have anywhere from 8gb to 50gb used. Any clue why some accounts dont use much at all compared to the 200gb ones? They all have chat messages turned of and afking the same type of farm in the same area.

I have been watching my own settings to when it comes to this and a few things do seem to affect the differences, like how many chunks are loaded, (server wise I believe that's the minimum forced?) altering how many chunks are loaded / seen could lower the amount of data being sent/received, however 77kbps (according to ORelio above) is quite a bit lower than having a full client online.

Besides this, data usage for 10 alts... wouldn't be impossible. it's fairly reasonable I'd say. Question for you though, you said the farms were the same? I wonder if that's accurate due to the range you have in what they use, try seeing what's different between them?

**Comment by jcodyparker** [comment]
I don't see any difference its 10 iron golem farms, all 100% exactly copied and same amount of mobs spawning. All have chat messages turned off (chathide)

**Comment by jcodyparker** [comment]
![Screenshot_20211005-034809~2](https://user-images.githubusercontent.com/90956620/135982011-b2499d45-a155-4c41-bea1-115ab5b5a42f.png)

**Comment by ORelio** [comment]
Maybe accounts on the outer farms don't have as many farms loaded than accounts in the inner farms? I don't really know what can be done client side because MCC does not "request" anything, it just reads (download) everything sent by server and discards unneeded data. If the server sends you less data (chunks, entity updates...) then it will consume less data on your internet access. As far as I know, chunks received from the server are set server side in config (server render distance), this is unrelated to the render distance set client side which only affects what is drawn on screen.

**Comment by jcodyparker** [comment]
Any more info on this? It's using like 3000gb per month in data and that is insane

**Comment by ReinforceZwei** [comment]
How about you use vanilla client to replace MCC and compare the data usage?
