### ISSUE TITLE
Is it possible to set up a report system using the respond feature

### ISSUE THREAD

**Issue by Isaac-Cooper** [MCCTeam/Minecraft-Console-Client#1787]
So i want to it so if 5 or people typed !report [ playername ] in chat it would ban the person who is listed in [ playername ], is this possible?

**Comment by Zippedy** [comment]
I personally believe that this would be the server side only unless the account using the MCC is an Operator on the server.

There are plugins that you could add to your server or suggest it to the server you play on so that if X amount of people vote on an event, such as "!report" the server console itself would push the vote through.

But if this is a MCC possible thing, I am sure you are not the only person with this suggestion!

**Comment by Isaac-Cooper** [comment]
Well, my idea is to create a !report command using the respond feature of minecraft console client, the bot will have op perms but i just need to find out how to register a vote
