### ISSUE TITLE
cant type while chatmode=enabled is on

### ISSUE THREAD

**Issue by EgeSisli** [MCCTeam/Minecraft-Console-Client#1813]
even tho i had chatmode=enabled on i still cant type any chat messages or commands

**Comment by EgeSisli** [comment]
it says chat is disabled in client options
![Screenshot_10](https://user-images.githubusercontent.com/83254565/140436475-653fcb5d-cf61-4ecf-be21-a713ba0fed99.jpg)

**Comment by ORelio** [comment]
You can try using the default settings from the example config file:

https://github.com/MCCTeam/Minecraft-Console-Client/blob/4ba09754de04a2d87fe921be6e7dd4b445edf2ad/MinecraftClient/Resources/config/MinecraftClient.ini#L90-L105

If that still does not work, try using a fresh Minecraft Console Client setup.
If that still does not work, check that chat works in vanilla Minecraft because MCC should not prevent you from chatting 😅

**Comment by EgeSisli** [comment]
ive solved the issue i died in console cleint and chat was flowing kinda fast so i didnt saw the you are dead message. and well you cant type when dead i got it but here is the thing, the error message i got was saying i got chat disabled in options not bc i was dead it was decieving,

**Comment by ORelio** [comment]
Indeed. Probably a plugin that did not handle the case where you try to speak while dead because you can't do this in vanilla minecraft (chat prompt is not accessible). At least it's solved 😄
