### ISSUE TITLE
faster movement

### ISSUE THREAD

**Issue by i7vlo** [MCCTeam/Minecraft-Console-Client#1934]
can you make the movements faster like regular minecraft walking ?

**Comment by Daenges** [comment]
In the current state: No.

Currently the pathfinding and walking mechancs are in a state, where they do their job. (Most of the time.)
They are clearly improvable and in the future, there needs to be an overhaul of them.

Unfortunately the pathfinding and walking algorithm are rather complicated  (see [Movement.cs](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Movement.cs) and its implementation of A*). As a result it costs a lot of time to read into the topic, just to be able to improve it. On top of that there are fewer and fewer people with enough time to apply changes.

So.. If you want to look into it and improve the general walking behaviour, feel free to do so. Otherwise you unfortunately need to live with the current state of operation. :/

**Comment by i7vlo** [comment]
i make it 1 nothing affected too

**Comment by i7vlo** [comment]
thanks i make it 4 its best and safe from anticheats

**Comment by ORelio** [comment]
Great! If you want to contribute, don't hesitate to add a setting to adjust speed and submit a pull request 😉

**Comment by milutinke** [comment]
It is possible to change, the speed, but this will get you banned on a lot of servers, as it was increased some time ago and we saw negative effects of people getting banned on Hypixel, now the speed is back to normal.
So if you need a faster speed, change the code to your preference and use case.
