### ISSUE TITLE
[Idea] carrot farm

### ISSUE THREAD

**Issue by X-nancy** [MCCTeam/Minecraft-Console-Client#1946]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Hello,
I play on minecraft server, this server farming is very important, I built a carrot farm with 6x6 blocks, I want to automate my carrot farm with console client bots, but I don't know how to do it, Use a hoe to destroy mature carrots or other mature crops.
can you help me? Thanks!

### Minecraft Version

1.16.5

### Device

Laptop

### Operating System

Windows

**Comment by Daenges** [comment]
I had a quick look into it. In contrast to sugar cane or cactus it gets more difficult here, since [Material.cs](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Material.cs) distinguishes between different crops, but not between their individual state of growth. This means, that you can currently detect, whether a certain block is a carrot or not, which makes cactus / [sugar cane farms](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/SugarCaneFarmer.cs) possible, since they rely on actually growing blocks, instead of block updates.

**Comment by milutinke** [comment]
Been looking at this, it's very tricky, as it involves a lot of bit manipulation of the Data field on the [`Chunk Data and Update Light`](https://wiki.vg/Protocol#Chunk_Data_and_Update_Light) packet.

**Comment by milutinke** [comment]
The bot is done for the most part, needs some polishing.
I'll open a PR when I can, like next week.

**Comment by milutinke** [comment]
Implemented in #2267
