### ISSUE TITLE
[Idea] Run more than 25 alts

### ISSUE THREAD

**Issue by AhYouWho** [MCCTeam/Minecraft-Console-Client#1995]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Yes

### Describe your problem

Hello I ran in to a problem where I can't run more than 25 alts when the on the 26 alt it said failed to login.
I try it many time with different alt and still doesn't work. So, I try to download one more console and put the other alts in and still doesn't work 

### Minecraft Version

1.8.9

### Device

Laptop

### Operating System

Windows

**Comment by luizhrios** [comment]
If you mean running 26 instances of MCC, as I think is not possible to run more than 1 user on each instance, this is probably a server limit.

**Comment by luizhrios** [comment]
If you mean running 26 instances of MCC, as I think is not possible to run more than 1 user on each instance, this is probably a server limit.

**Comment by AhYouWho** [comment]
I don't think that is the problem because I've the mod on the server they said I can have as much alts as I want.

**Comment by ORelio** [comment]
We did not hardcode such limit in MCC, so maybe there is a limit elsewhere:
 - On some older Windows systems you might have a limit of concurrent TCP connections: <https://stackoverflow.com/questions/413110/which-is-the-maximum-number-of-windows-concurrent-tcp-ip-connections>
 - The server might also limit the amount of concurrent connections by IP address as a ddos protection. The mod you talked to might be unaware of that because almost nobody would want to connect that many alts simultaneously, and maybe that was set as a default by whatever software they are using.

**Comment by milutinke** [comment]
Use a proxy
Here is a manual on how to use it: https://mccteam.github.io/guide/configuration.html#proxy
