### ISSUE TITLE
[BUG] The authentication or decryption has failed

### ISSUE THREAD

**Issue by Skidplays** [MCCTeam/Minecraft-Console-Client#1996]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18

### Console Client Version

20220407-17

### Expected Behavior

Expected to be able to login

### Actual Behavior

Crashes after typing email and password

### Steps to Reproduce the bug

1. Type email and password
2. 
3. 

### Attach screenshot here (If applicable)

![Capture](https://user-images.githubusercontent.com/22415446/163706408-4bd278a8-075f-40cd-aabb-051985e0552f.PNG)

### Device

VPS

### Operating System

Linux

**Comment by milutinke** [comment]
This is a problem with Mono, most likely, since it is no longer used, I'll close the issue.
This should not happen on .NET, if it does, feel free to re-open the issue.
I recommend installing the latest .NET 6.0 version.
It also could be that local certificates were revoked or expired, google how to update them if you have issues on .NET 6.0.
