### ISSUE TITLE
[Question] Why so bad?

### ISSUE THREAD

**Issue by Dm5Xia9** [MCCTeam/Minecraft-Console-Client#2048]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Why is the code so bad? I had to spend a lot of time refactoring. There is still a lot of work to be done https://github.com/Dm5Xia9/Bundle

### Minecraft Version

1.18.2

**Comment by ORelio** [comment]
Hi,
This project is 10 years old, and had 300+ pull requests from [various contributors](https://github.com/MCCTeam/Minecraft-Console-Client/graphs/contributors).
It has currently no dedicated maintainer since I stopped playing Minecraft like 4 years ago.
Updates are still provided by the community, but I can invest only limited time to review pull requests.
Don't hesitate to contribute if you think you can maintain the project in a better shape; we are looking for maintainers 🙂
A big project would, for instance, upgrade MCC to .NET5, see #1674.

**Comment by Dm5Xia9** [comment]
I'm creating an extended library to work with minecraft. I am interested in writing an implementation of your program based on it

**Comment by ORelio** [comment]
It would be nice indeed to move the protocol part to a library, or use an existing library that would be better maintained.
However, that's a huge task given the size of the project 🙂
