### ISSUE TITLE
I need help pls

### ISSUE THREAD

**Issue by iamkurcze** [MCCTeam/Minecraft-Console-Client#2060]
A server that i play on has implemented a GUI captcha.
Is there a way to create a c# script that clicks a specific item in Gui? Type of the item depends on name of gui.

**Comment by Daenges** [comment]
Unfortunately there is no template for this. You can either write your own C# script and work with the [inventory classes](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/Inventory) or utilize [inventory handling](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Resources/config/MinecraftClient.ini#L36) and try to solve this captcha with `/inventory` manually.

**Comment by Daenges** [comment]
Currently this repository is a bit cluttered, since the major `.Net 5` rework (from `.Net Framework 4.8`)  got merged.
*Although it is not really necessary for you to know, here is a [video](https://youtu.be/4olO9UjRiww) that explains what this means.*

Normally you would start with Visual Studio and create a new ChatBot in the [corresponding folder](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/ChatBots) that inherits from [ChatBot.cs](https://github.com/MCCTeam/Minecraft-Console-Client/blob/previous/MinecraftClient/ChatBot.cs).
**Make sure to change branch to `previous`, as the ChatBot.cs got removed in the latest commit.** 
I also do not really know what the plan behind this is tbh...

Then you need to add a `using MinecraftClient.Inventory;` to the top. By inheriting from `Chatbot.cs` you get some functions to work with inventories, which are explained by comments ([example](https://github.com/MCCTeam/Minecraft-Console-Client/blob/previous/MinecraftClient/ChatBot.cs#L1268)). Apart from that you can read through [inventory.cs](https://github.com/MCCTeam/Minecraft-Console-Client/blob/previous/MinecraftClient/Commands/Inventory.cs) (provides the usual command handling with `/inventory`) and the [inventory folder](https://github.com/MCCTeam/Minecraft-Console-Client/tree/previous/MinecraftClient/Inventory). 
You need to read through some code, but it is pretty similar to Java, so reading itself should not pose a big challenge.

**Comment by Daenges** [comment]
[This function](https://github.com/MCCTeam/Minecraft-Console-Client/blob/previous/MinecraftClient/McClient.cs#L978) returns all inventories as [Container](https://github.com/MCCTeam/Minecraft-Console-Client/blob/previous/MinecraftClient/Inventory/Container.cs) class (Keep in mind that container `ID 0` is the player inventory). If you look at the attributes you can see that every container has a `Title` and a dictionary `Items`. Just compare the title to [item.DisplayName()](https://github.com/MCCTeam/Minecraft-Console-Client/blob/previous/MinecraftClient/Inventory/Item.cs#L56) until you find the correct slot. And then it is only moving this item (here you can take a look into `inventory.cs` again).

**Comment by AxxGREG** [comment]
thx ill try my best

**Comment by ReinforceZwei** [comment]
> Make sure to change branch to previous, as the ChatBot.cs got removed in the latest commit.

@Daenges They were moved to `Scripting` folder.

**Comment by AxxGREG** [comment]
also how to preform command like /inventory from c# code ??

**Comment by Daenges** [comment]
> also how to preform command like /inventory from c# code ??

You don't. Use the appropriate functions gained from using the inventory namespace.

Above I provided sections where you see example usages or explanations for functions that may be useful. If you look into the `/inventory` file to see example calls.

**Comment by AxxGREG** [comment]
oh ok

**Comment by AxxGREG** [comment]
i get this: System.InvalidOperationException: ID expected

**Comment by AxxGREG** [comment]
```
//MCCScript 1.0

MCC.LoadBot(new RepairStoneGenerator());

//MCCScript Extensions

public class RepairStoneGenerator : ChatBot 
{
       private void passCaptcha(Container container) {

        String title = container.Title;
        ItemType itemType = ItemType.Arrow;

        foreach(var item in container.Items.) {

            int position = item.Key;
            ItemType iT = item.Value.Type;

            if (iT == itemType) {

                //preform /inventory container click position; wait 20;
                LogToConsole("Done!!!")
                break;

            }


        }


    }
   
   
    public override void Initialize()
    {
        LogToConsole("Bot enabled!");
        passCaptcha(GetInventories()[1]);
    }

}
```

**Comment by Daenges** [comment]
I can not debug it currently. As an advice: Try to open it in Visual Studio and create a new class or paste your script into the TestBot.cs. There you have more options to debug. Remember to `use inventory` and add the testbot to the [loading list](https://github.com/MCCTeam/Minecraft-Console-Client/blob/d9f1a77ac225aa556fde2dc8510b68b26043b8d4/MinecraftClient/McClient.cs#L218) to make it start.

**Comment by AxxGREG** [comment]
Everything works perfectly, just last question, how to, using c# code, click a inventory slot.
I'd like to achieve the same effect as `/inventory container click <slot>`, oh and how to preform `/inventory container close` ?

**Comment by AxxGREG** [comment]
> Have a look into the `Inventory` command file. [Here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Commands/Inventory.cs#L90) and [here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Commands/Inventory.cs#L117).

Amazing, how to get the handler ?, cuz im lookin at [https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Scripting/ChatBot.cs](url) and i see this:` //Handler will be automatically set on bot loading, don't worry about this`, idk what to do..

**Comment by milutinke** [comment]
is the captcha displayed through a chest GUI or a map?

**Comment by iamkurcze** [comment]
hey, ive written the bot, but it says that`[MCC] Script failed to clean-up` idk what to do

**Comment by breadbyte** [comment]
> > hey, ive written the bot, but it says that`[MCC] Script failed to clean-up` idk what to do
> 
> That is a normal warning, it should work normally if you don't have a compilation error.

Discussion was continued in #2204

**Comment by milutinke** [comment]
I guess that wraps up this Issue.
I'll close it in favor of that one.
