### ISSUE TITLE
Client Logs in from previous email account/ client used [BUG] 

### ISSUE THREAD

**Issue by TenReeez** [MCCTeam/Minecraft-Console-Client#2075]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2 Paper

### Console Client Version

6th of may Release

### Expected Behavior

Every time I click and open a new console client and I click on a different email account it should log that account in.

As it always has done.

### Actual Behavior

When I click on email to log in, it takes me to the previous email account entered. 
IE:   I log in using 1@hotmail.com (works fine)
Then I click and open up a new client with next email:  2@hotmail.com,  Click on link in web browser to paste into client but it Loads up 1@hotmail.com account.

### Steps to Reproduce the bug

1.  Try and log in multiple accounts via different emails
2. as above
3. as above

### Device

Desktop

### Operating System

Windows

**Comment by breadbyte** [comment]
Are you using the `browser` login method instead of `mcc`?

If so, the following fixes will work for you:

- use `mcc` login method instead of `browser`
- Go to microsoft.com and log out the previous account
- Use a different browser 
- Use incognito / private mode and login to the other account.

The reason why it logs in the previous account is because the currently logged in account in your browser is the previous one, and it uses that account to go through the login process. 

This is not something we can make changes in as this is simply how the browser method works for microsoft login. It uses the account currently logged in on the browser.

**Comment by BruceChenQAQ** [comment]
breadbyte's answer should have solved this issue, if you still have questions, fell free to reopen this issue.
