### ISSUE TITLE
[BUG] websocket-server.dll

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2117]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

https://github.com/MCCTeam/Minecraft-Console-Client/pull/1608
i dont see two dll libaries on https://github.com/MCCTeam/Minecraft-Console-Client/pull/1608

### Actual Behavior

https://github.com/MCCTeam/Minecraft-Console-Client/pull/1608
i see two dll libaries on https://github.com/MCCTeam/Minecraft-Console-Client/pull/1608

### Steps to Reproduce the bug

1. 
2. 
3.

**Comment by milutinke** [comment]
You need to compile:
https://github.com/ReinforceZwei/websocket-server
https://github.com/ReinforceZwei/simple-discord-api

And then you will have DLL files.

**Comment by deosync** [comment]
i can`t comiple

**Comment by deosync** [comment]
compile

**Comment by milutinke** [comment]
Note that this is not a merged feature yet, just a proposal.
And most likely it is going to be replaces with a library from NuGet.
In order to compile those 2 projects, you need Visual Studio 2022 configured for C# Development, install it, open the `.sln` file and when it loads in, press F6, that should build it.
The build file will be in the `bin/something...` directory.
