### ISSUE TITLE
My bot will automatically disconnect from the server after 60 seconds

### ISSUE THREAD

**Issue by resvz** [MCCTeam/Minecraft-Console-Client#2144]
I'm not sure if the server uses plug-ins to restrict robots, Is there a solution?

### **console log:**
[MCC] Disconnected by Server :
[MCC] 连接超时
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

### **server ip:**
mchmy.cn:25565

**Comment by BruceChenQAQ** [comment]
应该是计分板处显示玩家延迟的插件要求客户端回应Ping数据包，长时间没有回应导致被踢出服务器了。

---

This server requires a response to a Ping packet, which is not implemented now.

Should be fixed in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2124/commits/db64515b786850b833be7947b2798c75bb88f299

Since the pull request is not currently merged, you can try this build: https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/bugfix_pre_build

**Comment by resvz** [comment]
非常感谢，测试了一段时间很稳定
