### ISSUE TITLE
[Question] A ChatBot (cs script) for mine block which I was looking at.

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2210]
Hi guys! Do u have a script to mine block which bot was looking at?
I have a script which mining a block which above player, or in front of player, but it is uncomfortable to use.
Thanks a lot!

**Comment by deosync** [comment]
use for  please

**Comment by milutinke** [comment]
The [ChatBot API](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Scripting/ChatBot.cs) does not contain a method to get a block where the player is looking at currently, but I think it could be done with [`GetYaw()`](https://github.com/MCCTeam/Minecraft-Console-Client/blob/aec38d83c767cf4fff64a6ad2b7dfcebb076e6ab/MinecraftClient/Scripting/ChatBot.cs#L1114) and [`GetPitch()`](https://github.com/MCCTeam/Minecraft-Console-Client/blob/aec38d83c767cf4fff64a6ad2b7dfcebb076e6ab/MinecraftClient/Scripting/ChatBot.cs#L1123) methods.
Otherwise you can use [`GetCurrentLocation()`](https://github.com/MCCTeam/Minecraft-Console-Client/blob/aec38d83c767cf4fff64a6ad2b7dfcebb076e6ab/MinecraftClient/Scripting/ChatBot.cs#L987) to dig a block where the bot is standing.

**Comment by BruceChenQAQ** [comment]
![image](https://user-images.githubusercontent.com/26017411/193409276-4b0fdcee-0c08-492b-a3ea-458d24e75b89.png)
![image](https://user-images.githubusercontent.com/26017411/193409417-c9260dd3-5ca2-4bcd-8029-64d2c3e8bfcd.png)

A simple version is implemented.
Since MCC currently cannot handle hitboxes precisely, all blocks are considered complete cubes.

**Comment by BruceChenQAQ** [comment]
Implemented in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2227.

**Comment by BruceChenQAQ** [comment]
This PR has been merged, just use `GetLookingBlock` in the script to get the block position.
