### ISSUE TITLE
The servers have a captcha.[Idea] 

### ISSUE THREAD

**Issue by WakizashiPC** [MCCTeam/Minecraft-Console-Client#2254]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

when you enter the server, you are given a map in your inventory on which numbers or letters are written
In order to pass the captcha, you need to write these numbers in the chat, but how to do this if the map is not visible?

### Suggest a possible solution

Show map in console

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/115373399/194758787-da4993ca-7031-4a32-868d-44f9454dad12.png)
![image](https://user-images.githubusercontent.com/115373399/194758797-e8914304-d1a5-40e1-95f8-3c428386cf61.png)

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
There is already a chat bot that can render a map.
If the map is now shown, find in which inventory slot it is usually and use inventory commands to move it to the hotbar and use `/changesolot` to get it into hands.
Also configure the Map chat bot to auto render it,
As for showing the map in the console, we already have that idea in mind since the chat bot was made, it will be added in the future, we can't yet give an estimate when it's going to be added.
Here is a documentation for using the inventory: https://mccteam.github.io/guide/usage.html#inventory

**Comment by milutinke** [comment]
Ps if you're playing on Holyworld, if I remember correctly the map is always shown, so you can simply turn on the Map Chat Bot and turn on the auto generating feature.
