### ISSUE TITLE
[BUG] mcc says it cant connect to the server

### ISSUE THREAD

**Issue by logibaer702** [MCCTeam/Minecraft-Console-Client#2262]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

latest I think not sure how to check

### Expected Behavior

connect to server

### Actual Behavior

it launches finds the ip and then says it cant connect because
![image_2022-10-11_162258074](http://i.pics.rs/66cwd.png)
 of something being to large or small

 

### Steps to Reproduce the bug

1. use dexter113 version
2. log on through Microsoft
3. log on to cosmicpvp.me

### Attach screenshot here (If applicable)

![image_2022-10-11_162607728](http://i.pics.rs/66cwd.png)

### Anythings that could help diagnosing the bug

```txt
this is on dexter113 console client after watching his video
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

cosmicpvp.me

**Comment by breadbyte** [comment]
Simply type in the minecraft version of the server after it says failed to ping this IP.

**Comment by logibaer702** [comment]
> Simply type in the minecraft version of the server after it says failed to ping this IP.

it is not lettings me type

**Comment by milutinke** [comment]
Use the official client builds, we do not provide any support for non-official builds.
The server in question is not a vanilla/notchian server, MCC is made to work only with the official implementation of the protocol.

**Comment by milutinke** [comment]
> > Use the official client builds, we do not provide any support for non-official builds. The server in question is not a vanilla/notchian server, MCC is made to work only with the official implementation of the protocol.
> 
> where can I download an official build

https://github.com/MCCTeam/Minecraft-Console-Client/releases

Also, do not use any non official client forks, especially those which do not provide the source code, because they could be malicious.

**Comment by milutinke** [comment]
Also, you're trying to connect to a domain name that is not pointing to a real minecraft server.
The server address is: `pvp0.cosmicproxy.net`

**Comment by breadbyte** [comment]
cosmicpvp.me seems to report a non-standard protocol version of `4294967295`, which is the maximum value for a `uint`.
The protocol version parser throws an OverflowException because we parse an `int`, at Protocol18, line 2151.

Forcing a protocol version doesn't seem to bypass this issue.
The bug still occurs here despite being ran on an unofficial build, but it would be nice if bug reports are made using official builds, since there could be newer official builds that have fixed a variety of issues and the possibility of additional code added in unofficial builds that make debugging hard.

Trying to change every single use of the protocolversion to use `uint` instead of `int` is very difficult due to the amount of code we need to comb through.

A simple fix might be to just simply forcefully ignore parsing the server information json object if we have a specified protocol version, but I haven't taken a look at the code path needed for this to happen.

Or we could just wrap the parse with a try/catch? Not really my type of fix because that sounds more like a bandaid rather than a true fix, but it's a possibility.

> Simply type in the minecraft version of the server after it says failed to ping this IP.
>> it is not lettings me type

I deleted my previous message because it seems I was incorrect (should have just edited it after the fact, that's what i get for staying up at 5am), forcing a protocol version doesn't seem to work, and additionally, the reporter seems to have autorelog on so they won't be able to type in a protocol version anyways.

> Also, you're trying to connect to a domain name that is not pointing to a real minecraft server.
The server address is: pvp0.cosmicproxy.net

The SRV record resolves just perfectly fine, however it doesn't seem to reflect on some notchian clients (notably on a vanilla 1.8 client, as the server forces you to join using a 1.8 client) and just breaks.

**Comment by logibaer702** [comment]
thanks for all the help I went with the most recent version and it works fine
