### ISSUE TITLE
[BUG]  Kicked for "movement related hacks" when using /move

### ISSUE THREAD

**Issue by andreivacariu** [MCCTeam/Minecraft-Console-Client#2275]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

Lastest

### Expected Behavior

After doing the /move x y z, it should go to the x y z location without being kicked for "Movement Related Hacks".

### Actual Behavior

After doing /move for a short distance, you are getting kicked by some anticheats for "Movement Related Hacks".

### Steps to Reproduce the bug

1. Use default MCC config
2. Enable AutoFishing, set the starting time at 20 secs and set the location to a 50 blocks away
3. Join a server, for example i joined play.stealgens.com and did /fish, and after that, the anticheat would kick you for "Movement Related Hacks".

### Anythings that could help diagnosing the bug

```txt
The config file is the default one, only with autofish enabled
```

### Device

VPS

### Operating System

Linux

### Server Address (If applicable)

play.stealgens.com (this bugs happen on other servers as well)

**Comment by milutinke** [comment]
This is due to anti cheat on the server you play.
We can not do much about it.

**Comment by andreivacariu** [comment]
I see. Could the movement thing be improved so it doesnt get flagged randomly? Or is strictly an issue with the anticheat?

**Comment by milutinke** [comment]
> I see. Could the movement thing be improved so it doesnt get flagged randomly? Or is strictly an issue with the anticheat?

At the moment nope, it requires a lot of work, but we have it as a plan to change the whole of the code for movement.
The problem is that bot movement can be detected easily, because bots usually round numbers when moving, players are too random, but you can't introduce that type of randomness with bots.

**Comment by BruceChenQAQ** [comment]
The bot is easily considered to be cheating when it performs movement in the Y-axis direction.

Try to level the ground or modify the position of the moving target so that it moves only horizontally.

Remember to try to use the latest build, that fixes an issue that was detected as cheating in other servers.
