### ISSUE TITLE
[Idea] telegran/discord bridge (only alerts)

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2316]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

latest

### Describe your problem

I want my bot to send me only alerts to discord or telegram (not the whole chat)

### Suggest a possible solution

add feature

### Minecraft Version

1.16.5

### Device

Laptop

### Operating System

Windows

**Comment by deosync** [comment]
nice 15 days

**Comment by milutinke** [comment]
> nice 15 days

Everyone who here contributes is a volunteer, they contribute to the project because they want to and they contribute in their free time. They're not paid to do so.
They're under no requirement or obligation to add any features requested by the individuals in any time limit.
You should know this, this is how open-source work. 
The world does not circle around you.
If you are not patient, learn how to code and add it yourself, simple as.
