### ISSUE TITLE
Own mods 

### ISSUE THREAD

**Issue by AyaanReddit** [MCCTeam/Minecraft-Console-Client#2354]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

The ability to add your own forge mods.

(also I would like to know if this client is safe to use on hypixel)

### Minecraft Version

1.8.9

### Device

VPS

### Operating System

Windows

**Comment by milutinke** [comment]
The MCC already has a mechanism that spoofs forge mods, so you do not need to list any, the server will send the mod list and the client will just confirm that it "has" them.
If you meant an ability to add mods like you would in a normal client, that is impossible to implement. Because the MCC is written in C# and it's written in a completely different manner than Minecraft game is written in Java and that the Forge is written.
As for Hypixel, a lot of people got banned, we would not recommend using it on there, because it's considered as cheating on that server.
If you really insist, change the branding info and do not use walking speed greater than 2.
But note that if an admin spots the bot you'll probably get banned.
