### ISSUE TITLE
[Idea] how get random nickname 

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2380]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

latest 

### Describe your problem

I don't know how get random nickname 
preview:"Mybot28369", "Mybot82648"

### Suggest a possible solution

random nickname

### Minecraft Version

1.16.5

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Currently not possible within the mcc iteself, but you could use an external tool to start a mcc with a random nickname by starting the process and using the command line parameters to pass in a random username generated by that external tool/script.
As for implementing this, I kind would like to hear what other maintainers think of this, because a feature like that could be used maliciously to spam/flood servers and thus can cause MCC to gain a bad reputation, just for example auto solving captchas would.

**Comment by breadbyte** [comment]
Implementing a feature like this directly into MCC is unnecessary, and the only time I could see this feature being used is to flood servers.

There are only very few legitimate reasons to have multiple bots with random characters and/or numbers in their name.

**Comment by milutinke** [comment]
I guess that closes the issue.
