### ISSUE TITLE
[Idea] In ChatFormat define in config user and message index

### ISSUE THREAD

**Issue by Lerkista** [MCCTeam/Minecraft-Console-Client#2498]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

When i have a UserDefined regex for chat, the function IsChatMessage don´t work, because in my regex the user and message location are in different index

### Suggest a possible solution

Maybe adding config like this:

```
[ChatFormat]
Builtins = false                            
UserDefined = true                          
Public = '^(.*)\[(.*)](.*) ([a-zA-Z0-9_]+)(.*)» (.+)$'
UserPublicIndex = 4
MsgPublicIndex = 6
```
Because in my chat format user is index 4 and message is index 6, and in IsChatMessage user are defined as 1 and message as 2

### Minecraft Version

1.19.4

### Device

Raspberry Pi

### Operating System

Linux

**Comment by breadbyte** [comment]
The first and second capturing groups are used to capture the username and the message content respectively.

Use `(?:)` to create a non-capturing group.

---

For example, given the following Regex string and the string to match,

Regex String = `(\[.*\]) (.*) » (.*)`
Text to match = `[RANK] breadbyte » Hello World!`

This will match the text with 3 groups.

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/14045257/e300717f-248a-4af3-ade2-2ba7df9bb36c)

But since the first and second groups are used for capturing the username and the message content, we need to make the first group a non-capturing group.

With the following change to our regex string:

Regex String = `(?:\[.*\]) (.*) » (.*)`

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/14045257/2c416ab5-0e1a-4637-9326-366322be7354)

It is still considered as a group by regex, but is not passed on to the application.

**Comment by Lerkista** [comment]
Thanks, that works
