### ISSUE TITLE
[Idea] Support for Bedrock

### ISSUE THREAD

**Issue by UniqueNIHAL** [MCCTeam/Minecraft-Console-Client#2605]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

20231011-230

### Describe your problem

Hii, could support for bedrock edition be added, with Microsoft giving bedrock accounts to java account users, it can be a great way to gain more afk-accounts with the Minecraft Console Client

If this is possible, it will be a great addition :)

### Minecraft Version

1.20

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
That would require the complete re-write of the client, since Bedrock uses a completely different protocol called Rak-Net, and there is very little info and for very old versions, since it's closed source and written in C++.
Bruce Chen is working on a protocol library re-write, after he completes it, maybe then we can think about adding older versions of Bedrock, but it would be complex and a very long process, and we have to first get all the currently supported Java versions implemented and tested with the new protocol library first.
So this is not going to be supported any time soon.

**Comment by UniqueNIHAL** [comment]
Ahh I understand

Cool thank you :)
